### ISSUE TITLE
download hd qr instead of image

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#10]
since we have moved to rendering qrContent instead of displaying image, need to make sure the download button will download the rendered qr instead of looking for image path.

![image](https://github.com/user-attachments/assets/f4eb0427-1475-4527-a0e6-0f9298984f4d)

**Comment by alserembani94** [comment]
Aku boleh amek ni, implementation lebih kurang macam AMA aku

**Comment by alserembani94** [comment]
Tapi kalau someone else nak amek pun boleh je

**Comment by khrnchn** [comment]
> Aku boleh amek ni, implementation lebih kurang macam AMA aku

the floor is yours sifu

**Comment by nrmnqdds** [comment]
nak ambik pls

**Comment by khrnchn** [comment]
> nak ambik pls

osom @alserembani94
