### ISSUE TITLE
suggestion to check whether institution already got qr or not

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#102]
show whether the institution already got QR or not, based on this [pdf](https://masjid.islam.gov.my/cetakMasjidDanSurau??carian=&jenis=&negeri=&daerah=&masjidSurau=)
![image](https://github.com/user-attachments/assets/9444817e-a844-4e55-9468-ecf5b0bc0f9a)

**Comment by Kyziq** [comment]
Banyaknya data dekat PDF tu 🤯, would be very useful
