### ISSUE TITLE
Map 🗺️

### ISSUE THREAD

**Issue by Kyziq** [khrnchn/sedekah-je#113]
Thoughts about making user able to toggle map on and off? At the moment tak banyak sangat features dekat map

**Comment by khrnchn** [comment]
tak pun hide terus on home, only display on individual institution page. @Altafxx wdyt

**Comment by Altafxx** [comment]
Aku terfikir macam mana tau, on header tu put it like 1 row above untuk slider tu

**Comment by Altafxx** [comment]
Wait sabar jap, otak still kat office apa aku comment kat atas ni

**Comment by Altafxx** [comment]
> tak pun hide terus on home, only display on individual institution page. @Altafxx wdyt

Seems kemas gak. But kalau nak bagi user enable or disable map. Probably pull from local storage? Default value to show map??

**Comment by Kyziq** [comment]
> tak pun hide terus on home

Hide on main page, add toggle map button untuk user?

**Comment by khrnchn** [comment]
> > tak pun hide terus on home
> 
> Hide on main page, add toggle map button untuk user?

tak sure lak, boleh kot at least tak buang terus lah mapnya

**Comment by imanazri** [comment]
> Thoughts about making user able to toggle map on and off? At the moment tak banyak sangat features dekat map

aku rasa map tu macam secondary, could be good to be able to toggle on/off (in accordion way)

sbb main hierarchy is nak tengok list masjids, and the map comes second

**Comment by khrnchn** [comment]
> > Thoughts about making user able to toggle map on and off? At the moment tak banyak sangat features dekat map
> 
> aku rasa map tu macam secondary, could be good to be able to toggle expand/collapse
> 
> sbb main hierarchy is nak tengok list masjids, and the map comes second

setuju sebab minggu lepas member aku ingat searchbar tak function, sekali dia tak tahu page boleh scroll (prolly sebab map besaq sangat)
