### ISSUE TITLE
Integration dengan analytics tools

### ISSUE THREAD

**Issue by alserembani94** [khrnchn/sedekah-je#116]
Sebabnya, kalau boleh, kita nak keep track page mana yang kerap visit, so kita tau which institution get how many visits.

For now, it can be less value, tapi will be good if kita start kumpul data on this.

Something like Google Analytics 4, atau something similar or better.

**Comment by Kyziq** [comment]
https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#google-analytics

**Comment by nrmnqdds** [comment]
or roll our own analytics

**Comment by alserembani94** [comment]
I am actually inclined towards this, since kita nak buat open source.

Unless ada lagi option yang open, then I am waiting for this solution to be rolled out.

Not that GA4 is not good enough, but need openness.

**Comment by Altafxx** [comment]
The only analytics yang ada is Google Search Console which currently only me having the access 
![ClipWindowsGIF](https://github.com/user-attachments/assets/218a190e-9ccb-4aeb-937a-cd74f6ac89da)

**Comment by luqmanafif96** [comment]
https://firebase.google.com/docs/analytics/get-started?platform=web how abt this one ?

**Comment by farhan-helmy** [comment]
I have sponsored analytics for this project

**Comment by khrnchn** [comment]
least generous homelab enjoyer
