### ISSUE TITLE
suggestions from khairulhaaziq

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#121]
![image](https://github.com/user-attachments/assets/2be4c69f-91aa-463b-8d1f-3df906cd6eac)

**Comment by Altafxx** [comment]
favourite? pakai indexed db might be good for this use case. since takde auth

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

**Comment by nrmnqdds** [comment]
solved #151
