### ISSUE TITLE
how do public contribute to the directory, other than forking the repository?

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#13]
* public who wish to upload qr to the website

**Comment by farhan-helmy** [comment]
invite as collaborator and kalau nak keep track, buat file codeowners. Sesiapa nak collab, fork send pr update codeowners

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by khrnchn** [comment]
what about a popup modal for the public to create an entry? (need auth)

![image](https://github.com/user-attachments/assets/fdb6ffda-670d-43f3-83ac-5629c6582bd8)

**Comment by farhan-helmy** [comment]
how did bro upload well squared image

**Comment by khrnchn** [comment]
> how did bro upload well squared image

just paste bro

**Comment by khrnchnv** [comment]
@luqmanafif96 tambah link google sheets dekat sini?

**Comment by khrnchn** [comment]
> > @luqmanafif96 tambah link google sheets dekat sini?
> 
> https://docs.google.com/spreadsheets/d/1JhjCv-5f0mb9upioVeWjYCqmLCGh3YL5rVbwR5AAB2A/edit?usp=sharing

ni with edit permission ke tak? baru perasan people might on in and change whatever they want haha

**Comment by khrnchn** [comment]
google form + auto import responses into google sheets?

**Comment by nrmnqdds** [comment]
admin dashboard when

**Comment by khrnchn** [comment]
@haziqzikry 's friend made a google form for this - https://forms.gle/sUvn5KteEXi6Ke8G9
