### ISSUE TITLE
clean up data

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#14]
1. make sure institution name and location capitalization are consistent~~
2. institution name & location yang pakai shortform/ incomplete
3. location naming (tak sure patut biar ke tak so that boleh filter by kawasan later)

**Comment by farhan-helmy** [comment]
Pakai helper capitalize first character, kalau nak cleanup makan masa hahah

**Comment by khrnchn** [comment]
capitalize [done](https://github.com/khrnchn/sedekah-je/issues/11)
