### ISSUE TITLE
Add disclaimer or FAQ

### ISSUE THREAD

**Issue by aerryasmani** [khrnchn/sedekah-je#143]
Most common Qs sepanjang 3 minggu promote dekat whatsapp/Instagram:
- Korang ambik cut ke derma ni?
- Sedekahjer ni project yang ada affliate dengan Alif Teega ke
- Kalau ada QR, nak submit macam mana.

Kalau kau okay, Aku provide content for this.
Doesnt have to be fancy, 
can put underline text on homepage

User flow 1:
User click > redirect page > FAQ + Disclaimer

User flow 2:
User click > Modal pop up > FAQ + Disclaimer

**Comment by khrnchnv** [comment]
nice idea juga

1. tak, since yang kita provide institutions punya qr. kalau depa donate memang directly into that institution's account
2. tak xd
3. ada button muatnaik qr (google form)
![image](https://github.com/user-attachments/assets/d12632e2-49a1-4c38-8aee-1f8728184cd8)

**Comment by aerryasmani** [comment]
Nice! Untuk content nanti aku bagi docs untuk kau refer. Thanks bang KC!

**Comment by aerryasmani** [comment]
@khrnchn Add the necessary information to help you to build this [Feature recommendation Docx](https://docs.google.com/document/d/1cWtOAHAyX-QwyfXrjS9yenplqjfuN_aDZy76Skxxne0/edit?usp=sharing)

**Comment by luqmanafif96** [comment]
> Most common Qs sepanjang 3 minggu promote dekat whatsapp/Instagram:
> 
> * Korang ambik cut ke derma ni?
> * Sedekahjer ni project yang ada affliate dengan Alif Teega ke
> * Kalau ada QR, nak submit macam mana.
> 
> Kalau kau okay, Aku provide content for this. Doesnt have to be fancy, can put underline text on homepage
> 
> User flow 1: User click > redirect page > FAQ + Disclaimer
> 
> User flow 2: User click > Modal pop up > FAQ + Disclaimer

affilate alif teega ni mmng 🤣
