### ISSUE TITLE
Recent Awareness: Maybank QR Merchant Name Allegedly Loophole 

### ISSUE THREAD

**Issue by kihonq** [khrnchn/sedekah-je#173]
Context:
https://twitter.com/mkhairulazri/status/1839563380186882380

Solution:
Ontah ler. Issues seems to be more top-down.
Maybank is looking into this allegedly loophole as we speak. So it might not even be a loophole after all to which I will close this issue.

But from our side, least we can do for now is to really analyze where the QRs coming from and under which account like explained here:
https://twitter.com/mkhairulazri/status/1839573632374501738

**Comment by khrnchn** [comment]
@kihonq someone already started to verify (paid 1 cent and view receipt, but somehow all the To Account: are empty)

**Comment by khrnchn** [comment]
added disclaimer in #174

**Comment by khrnchn** [comment]
also added source of qr when inserting a new entry for future reference
