### ISSUE TITLE
qr verification to make sure qr code is legit

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#18]
currently we're using manual verification, where we used scanner in MAE and TNG to check the account name.

**Comment by topekuno** [comment]
We could probably add a checkmark for now after manual verification.
Maybe tie in with government database here: https://masjid.islam.gov.my/maklumatMasjidSurau
Or maybe higher number of scans from different people > higher probability is legit?
Just putting out suggestions

**Comment by imanazri** [comment]
possible ke nak track scanned count? @khrnchn

**Comment by khrnchn** [comment]
> possible ke nak track scanned count? @khrnchn

tak pernah explore pula pasal ni

**Comment by salfaris** [comment]
> possible ke nak track scanned count? @khrnchn

agak susah nak implement tu.

maybe boleh add input untuk tanya user "did you scan this?" atau "have you been to this masjid/surau?". Ni style linkedin bila kita tengok job ad nanti dia tanya "did you apply?".
