### ISSUE TITLE
GetDoa Integration Feature Suggestion

### ISSUE THREAD

**Issue by aerryasmani** [khrnchn/sedekah-je#180]
GetDoa
I think we should add the GetDoa under the QR code
![image](https://github.com/user-attachments/assets/d19bfae3-82a5-4a8a-a9ac-2c79058291c1)
and rescale the QR card so that the GetDOA can be seen in the same page as the QR.

Additional Thoughts:
- Translation button to translate some text to accommodate getdoa API.
- Default state is in 'Bahasa Malaysia' I think we can just ignored the category name from the APIs
- The doa card should use this structure for now:
- ![image](https://github.com/user-attachments/assets/6eaff89d-6038-4fda-8e08-0591071cfec1)

Another enhancement i can see moving forward for Sedekahje are
- Mapping the GetDOA 'Name' param to the time or the institution/festivity.
But for this need to study further the API will getback to you.

**Comment by khrnchn** [comment]
cantik, thanks for the suggestion broski

**Comment by nrmnqdds** [comment]
getdoa dah ada api ke @Hazqeel09

**Comment by khrnchn** [comment]
@Hazqeel09 sorry. u. lama tak sambung. 🫦

**Comment by Hazqeel09** [comment]
takpe u, cuma nanti belanja bunga satu

**Comment by nrmnqdds** [comment]
> https://v3.getdoa.com/api/randomDoa
> 
> @nrmnqdds

website aok down ke

**Comment by Hazqeel09** [comment]
@nrmnqdds aku tengah tukar infra HAHAHAHAHAH will let you know lepas aku letak new api

**Comment by Hazqeel09** [comment]
@nrmnqdds @khrnchn 

udah bisa access through https://getdoa.com/api/random-doa
