### ISSUE TITLE
insert QRs from facebook post's comments

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#183]
source - https://www.facebook.com/iera.aqila.3/posts/pfbid02kuuKrSq2both4vHJZg5SCZBp3oWp7cvhQSc9KmgAbit6KjXWu7nGMWfkBXWbqzHBl

update:
new source - https://www.facebook.com/zaini.wahab.372/posts/pfbid0HSD11u7fmPZVFfMXUerP3qyVtwermKhCULGqTaFvcLNPfiEct1ZzqPAeGSc9u5UTl

please crosscheck first whether it has been listed on the website.

**Comment by iqfareez** [comment]
On it. I'll start with first 25 QRs first, giving opportunity to others to also contribute
