### ISSUE TITLE
randomizer button (?) that randomly picks a qr for user to donate

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#19]
something like 

> tak pasti nak derma ke mana? tekan saya

idea from:

![image](https://github.com/user-attachments/assets/1ee7aeef-95cf-4ea8-a723-36f586434a4f)

**Comment by aerryasmani** [comment]
Make it that either the randomizer tu tak akan bagi Qr sama. or 
Until the count reset either every month or if  semua QR user dah derma. So every Sejid have equal opportunity kalau guna this randomizer.

**Comment by khrnchn** [comment]
> Make it that either the randomizer tu tak akan bagi Qr sama. or Until the count reset either every month or if semua QR user dah derma. So every Sejid have equal opportunity kalau guna this randomizer.

cane nak track qr tu user dah derma?

**Comment by aerryasmani** [comment]
> Masa korang convert to high res QR, korang boleh assign unique id to the QR? and moving foward use that on randomizer?

> > Make it that either the randomizer tu tak akan bagi Qr sama. or Until the count reset either every month or if semua QR user dah derma. So every Sejid have equal opportunity kalau guna this randomizer.
> 
> cane nak track qr tu user dah derma?

Masa korang convert to high res QR, korang boleh assign unique id to the QR? and moving foward use that on randomizer? If macam banyak kerja on your side, we stick to the randomizer tu jelah i guess

**Comment by alserembani94** [comment]
aku amek ni

**Comment by khrnchn** [comment]
> aku amek ni

ah, bros boutta cook with this one too
