### ISSUE TITLE
[addQR] Add New QR Code

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#192]
**Type of Institute:**
- Surau

**Name of the Masjid:**
_(Surau Al Bayan)_

**Name of the City:**
_(Rawang)_

**State:**
- Selangor

**QR Code Image:**
_(https://ibb.co/wWDVCsc)_

**Comment by khrnchn** [comment]
@khursani8 betul tak format aku replace ni? xd anyway nanti aku check balik [this one](https://github.com/khrnchn/sedekah-je/actions/runs/11732894059)

**Comment by khrnchn** [comment]
done update workflow settings

![image](https://github.com/user-attachments/assets/f66e843d-5ecf-4b0d-8b74-f19547e84efc)

**Comment by khursani8** [comment]
> **Type of Institute:**
> 
> * Surau
> 
> **Name of the Masjid:** _(Surau Al Bayan)_
> 
> **Name of the City:** _(Rawang)_
> 
> **State:**
> 
> * Selangor
> 
> **QR Code Image:** _(https://ibb.co/wWDVCsc)_

Should be mcm ni

Type of Institute:
Surau

Name of the Masjid:
Surau Al Bayan

Name of the City:
Rawang

State:
Selangor

QR Code Image:
https://ibb.co/wWDVCsc

**Comment by khrnchn** [comment]
tengah update jap workflow, error tu dia suh pull dulu

**Comment by khursani8** [comment]
> tengah update jap workflow, error tu dia suh pull dulu

ohh,aku try tadi ok je
