### ISSUE TITLE
[addQR] Add New QR Code

### ISSUE THREAD

**Issue by khursani8** [khrnchn/sedekah-je#193]
**Type of Institute:**
Surau

**Name of the Masjid:**
Surau Al Bayan

**Name of the City:**
Rawang

**State:**
Selangor

**QR Code Image:**
https://ibb.co/wWDVCsc

**Comment by khursani8** [comment]
close because qr image not directly to image link https://i.ibb.co/FwG2JVH/SURAU-AL-BAYAN-KHK-STICKER.jpg

**Comment by khrnchn** [comment]
> close because qr image not directly to image link https://i.ibb.co/FwG2JVH/SURAU-AL-BAYAN-KHK-STICKER.jpg

ahhh patutlah hahaha
