### ISSUE TITLE
[addQR] add new qr code for Madrasah As-Salam

### ISSUE THREAD

**Issue by sitisarahaqilah** [khrnchn/sedekah-je#224]
**Type of Institute:**
Surau

**Name of the Masjid:**
Madrasah As-Salam

**Name of the City:**
Alai

**State:**
Melaka

**QR Code Image:**
https://files.fm/f/mktss945e5

**Comment by khrnchn** [comment]
@sitisarahaqilah can see this https://github.com/khrnchn/sedekah-je/pull/225#issuecomment-2463910273
