### ISSUE TITLE
Add more payment options UI

### ISSUE THREAD

**Issue by haziqzikry** [khrnchn/sedekah-je#24]
Ada masjid guna other QR macam Boost. 

eg. Masjid Saidina Umar Al-Khattab, Bukit Damansara, Kuala Lumpur ada Boost QR and also duitnow

![masjid bd boost qr](https://github.com/user-attachments/assets/3c9ed652-be86-455e-b6f8-20d39a22b346)

**Comment by khrnchn** [comment]
mantap, memang plan nak tambah sebab ada jumpa [pdf ni](https://www.rhbgroup.com/-/media/Microsites/syuqr/files/Senarai_31_Institusi_Berdaftar_dgn_syuQR_02042019_V2.pdf)
