### ISSUE TITLE
 Add New QR Code Masjid UTP and Masjid Ar Raudhah

### ISSUE THREAD

**Issue by luqmanafif96** [khrnchn/sedekah-je#273]
**Type of Institute:**
- Masjid

**Name of the Masjid:**
- Masjid An-Nur , UTP 
-  Masjid Ar-Raudhah  

**Name of the City:**
- Seri Iskandar 
- Sitiawan

**State:**
- Perak 

**QR Code Image:**
http or https something

![Masjid_Ar-Raudhah_sitiawan](https://github.com/user-attachments/assets/dc6c3f1b-a7e5-4279-b621-1481b6e23542)

![Masjid_An-Nur_UTP](https://github.com/user-attachments/assets/9796d414-2de4-4c5f-bf46-76ec53fed0eb)

**Remarks:**
{name}, {source} - {url} (eg: khairin, facebook - facebook.com/something) example: https://github.com/khrnchn/sedekah-je/blob/main/app/data/institutions.ts#L8835
{luqman afif}, {self and friend}

**Comment by khrnchn** [comment]
tak sapot multiple lagi weh kalau guna issues. takpe aku buatkan jap
