### ISSUE TITLE
[addQR] add new qr code for {institution name}

### ISSUE THREAD

**Issue by sykrwasd** [khrnchn/sedekah-je#283]
![Uploading IMG_0776.jpeg…]()
**Type of Institute:**
- Others

**Name of the Masjid:**
e.g., Pusat Islam UiTM Tapah

**Name of the City:**
e.g., Tapah Road

**State:**
- Perak

**QR Code Image:**
http or https something

**Remarks:**
{name}, {source} - {url} (eg: khairin, facebook - facebook.com/something) example: https://github.com/khrnchn/sedekah-je/blob/main/app/data/institutions.ts#L8835

**Comment by khrnchn** [comment]
hi @sykrwasd , can you re-edit the qr image or provide the link here? ill help update the pr
