### ISSUE TITLE
Random Doa 'Tag' and 'Powered By: GetDoa' overlapping with the doa and translation.

### ISSUE THREAD

**Issue by aerryasmani** [khrnchn/sedekah-je#289]
Issue:
Doa Tag and footer are overlapping with the content. 
Tested on 3 physical device and screen emulator.
Issue with small device with specs below. If this by design, can just close the report KC/Qud

Tested on :
Device model: Samsung S24 based model
OS: Android 14 w One UI Ver 6.1
Screen Size: 6.2 Inch
Screen Dimension: Width: 393px x 852px

![image](https://github.com/user-attachments/assets/a0450ac1-a87d-4e16-a77d-c146c6268155)
![image](https://github.com/user-attachments/assets/ca6885d8-4b5c-43bd-8fe5-caee5a4aeba3)

**Comment by khrnchn** [comment]
![image](https://github.com/user-attachments/assets/7c4822d1-0a57-4616-bd62-b36177116566)
![image](https://github.com/user-attachments/assets/35cc5b7c-f6fa-404a-ba36-62eb54c533c9)

ok kot noh

**Comment by khrnchn** [comment]
btw aku strip [] juga
