### ISSUE TITLE
Copy button

### ISSUE THREAD

**Issue by Kyziq** [khrnchn/sedekah-je#32]
Belum ada lagi implementation untuk handle `onClick` dekat copy button. Is it supposedly will copy to clipboard the QR image?

![image](https://github.com/user-attachments/assets/29d82769-da18-4cb9-b46d-ff690d6bfde5)

**Comment by nrmnqdds** [comment]
kalau image tu boleh try copy tak both jpg dengan png naktengok

**Comment by Kyziq** [comment]
> kalau image tu boleh try copy tak both jpg dengan png naktengok

```js
const item = new ClipboardItem({ "image/png": blob });
```

pakai `ClipboardItem`, boleh specify nak pakai image type apa, I believe .png format is ok in this case

**Comment by nrmnqdds** [comment]
yea cuma iirc ClipboardItem cuma allow png. kalau manually format gitu taksilap aku takjadi and have to manually convert to png, since certain gambar dalam data tu is jpeg

**Comment by nrmnqdds** [comment]
tapi kalau kau buat okay je then okay jela kot

**Comment by khrnchnv** [comment]
what if change copy icon -> share icon, then share icon guna shadcn DropdownMenu, ada options:

1. copy image to clipboard
2. share to whatsapp
3. share to twitter

**Comment by Altafxx** [comment]
> what if change copy icon -> share icon, then share icon guna shadcn DropdownMenu, ada options:
> 
> 1. copy image to clipboard
> 2. share to whatsapp
> 3. share to twitter

lgtm

**Comment by nrmnqdds** [comment]
no way we got kc ds acc before gta 6 @khrnchnv
