### ISSUE TITLE
cleanup: check redundant QR and spellings

### ISSUE THREAD

**Issue by haziqzikry** [khrnchn/sedekah-je#45]
- Check for redundant QR codes

1 spotted so far: Masjid Seksysen 7 Shah Alam

![image](https://github.com/user-attachments/assets/6ce96748-5603-474c-bc1d-675400b6fc22)

- Cleanup and standardize some masjid/surau names

**Comment by haziqzikry** [comment]
admin view soon?? (not filament)

**Comment by khrnchn** [comment]
> admin view soon?? (not filament)

bro just setup ETL to clean up the mosques data or sumn idk /s

**Comment by khrnchnv** [comment]
se7, sebab ada QRs yang guna shortform, etc

**Comment by haziqzikry** [comment]
ETL in here is crazy lets do it /s
