### ISSUE TITLE
bug in sedekahje.com/rawak

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#49]
@alserembani94 

https://github.com/user-attachments/assets/03b5b6a7-0de9-47d5-b883-3dfbe5e004e6

**Comment by khrnchn** [comment]
yang takde qr tu sebab takde qrContent, nak includekan sekali juga ke masa shuffle?

**Comment by alserembani94** [comment]
OH YA AKU LUPA

Include je macam biasa, tapi sebab styling aku tukar sikit je.

Nanti aku fixkan.
