### ISSUE TITLE
create python script to automate data extraction from QR

### ISSUE THREAD

**Issue by Hazqeel09** [khrnchn/sedekah-je#50]
currently working on this

tapi kalau takmo benda ni, roger

**Comment by luqmanafif96** [comment]
nice nnty share repo abe ,
so far aku letak dalam ni https://docs.google.com/spreadsheets/d/1JhjCv-5f0mb9upioVeWjYCqmLCGh3YL5rVbwR5AAB2A/edit?usp=sharing

**Comment by khrnchnv** [comment]
rasa yang ni @farhan-helmy dah buat & dah guna untuk extract 189 qr dari [pdf muamalat](https://www.muamalat.com.my/wp-content/uploads/2023/10/LIST-OF-QR-CODE-FOR-E-DERMA.pdf) haritu (kot). cuba adjust repo

**Comment by khrnchnv** [comment]
> nice nnty share repo abe , so far aku letak dalam ni https://docs.google.com/spreadsheets/d/1JhjCv-5f0mb9upioVeWjYCqmLCGh3YL5rVbwR5AAB2A/edit?usp=sharing

requested access for this

**Comment by luqmanafif96** [comment]
> > nice nnty share repo abe , so far aku letak dalam ni https://docs.google.com/spreadsheets/d/1JhjCv-5f0mb9upioVeWjYCqmLCGh3YL5rVbwR5AAB2A/edit?usp=sharing
> 
> requested access for this

Approved as editor

**Comment by topekuno** [comment]
Made an attempt here. Extract qr from pdf then extrapolate data from qr content
https://github.com/topekuno/sedekah-qr-extractor

Made a pull request #78 after using scripts
Need further refining and cleanup as seen in comments of pull request

**Comment by luqmanafif96** [comment]
imma create the own kiddies script to automate from cv insert .ts file 

https://github.com/luqmanafif96/sedekahjer_QRreader
