### ISSUE TITLE
Suggestion : adding field for daerah 

### ISSUE THREAD

**Issue by luqmanafif96** [khrnchn/sedekah-je#64]
semua data masjid bercampur dengan negeri dan daerah utk 'location' dan impact dkt filter negeri , 
treat as Tech Debt or improvement add the field untk daerah

**Comment by khrnchnv** [comment]
yang tu rasa @Kyziq tengah buat (kot)

**Comment by Kyziq** [comment]
WIP. Dah 50% of total 3k lines

**Comment by khrnchn** [comment]
> WIP. 
> 
> - Add state, city replacing location.
> 
> - Correct typos
> 
> - Streamline data
> 
> - Dapat jumpa yang duplicate
> 
> - Dapat tahu ada masjid yang tukar nama this year
> 
> etc
> 
> 
> 
> Dah 50% progress, kena make sure setiap satu data preciseee

damn thats a lot of effort ☠️ minta ytm bagi double allowance next month hahaha

**Comment by Kyziq** [comment]
> semua data masjid bercampur dengan negeri dan daerah utk 'location' dan impact dkt filter negeri , treat as Tech Debt or improvement add the field untk daerah
Betul, current implementation of filter for states dropdown, actually not correct. Macam filter tak jumpa masjid untuk Kedah. Jadinya perlukan type `state` for better result

**Comment by Kyziq** [comment]
> damn thats a lot of effort ☠️ minta ytm bagi double allowance next month hahaha

HAHAHAHA nakkkk 🤩🤩

**Comment by luqmanafif96** [comment]
patut tmbh "buy me coffee" or donate patreon
