### ISSUE TITLE
rhb data by kamarul adha

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#67]
huge thanks to kamarul for crawling & extracting data from rhb's jomderma website. 

https://huggingface.co/datasets/Hiraishin/RHB/blob/main/rhb-full.jsonl

source: https://www.rhbgroup.com/jomderma/index.html

**Comment by khrnchn** [comment]
after scanning surau darul madinah's qr, it shows tadika sin hwa's name. error from rhb's side.

thats all for now

**Comment by khrnchn** [comment]
turns out dekat main page qr dia tadika sin hwa, but modal view betul pula qr nya. 

`00020201021126580014A000000615000101065641600226126102000005251RHBQR0136115204739953034585802MY5919Surau Darul Madinah6002MY61059815062300309ROA0198010713A0420170087A28264BF4A3168CA26A3EDD503AA94C04D7BE730247A580C18F5D9636BC7010C009CDD63040FBB`

https://github.com/user-attachments/assets/2472d4b7-da35-4801-b389-9193c761bfce

**Comment by KamarulAdha** [comment]
All 84 QR codes:

Data:
https://huggingface.co/datasets/Hiraishin/RHB/blob/main/rhb-completed.jsonl

Images:
https://huggingface.co/datasets/Hiraishin/RHB/blob/main/qr_images_full.zip
