### ISSUE TITLE
view page for single qr

### ISSUE THREAD

**Issue by khrnchn** [khrnchn/sedekah-je#69]
1. add a view page for single qr
2. url is like sedekahje.com/institutions/[slug] (maybe slugify the institution's name)
3. add share options on main page

**Comment by Altafxx** [comment]
Noice number, assign this to me

**Comment by Kyziq** [comment]
Kalau yang 1, 2 tu, maybe can redirect to the unique page by clicking the institution's name.
Tapi kan, nampak macam redundant dengan gambar bawah ni, which is clicking QR
![image](https://github.com/user-attachments/assets/28a5f34f-bd0b-49f9-ab0b-00e7b4195fa7)

**Comment by Altafxx** [comment]
> Kalau yang 1, 2 tu, maybe can redirect to the unique page by clicking the institution's name.
> Tapi kan, nampak macam redundant tak dengan gambar bawah ni, which is clicking QR
> ![image](https://github.com/user-attachments/assets/28a5f34f-bd0b-49f9-ab0b-00e7b4195fa7)
> 

Was thinking for 1, click je anywhere dekat card tu. Sebab currently image QR tu je trigger modal.

For number 3, right now the share icon just copy qr to clipboard je. Instead of that, aku terfikir nnty akan ada drawer yang ada multiple share (copy qr, copy url, whatsapp, yada yada)

**Comment by Kyziq** [comment]
> Was thinking for 1, click je anywhere dekat card tu. Sebab currently image QR tu je trigger modal.

Ok jugak, nanti after navigate, dekat page tu boleh letak more information macam the social links, etc

> For number 3, right now the share icon just copy qr to clipboard je. Instead of that, aku terfikir nnty akan ada drawer yang ada multiple share (copy qr, copy url, whatsapp, yada yada)

Yup, dah letak TODO dekat dropdown, boleh uncomment nanti
